- README.md
- lua/lint.lua
- lua/lint/linters/inko.lua
- lua/lint/util.lua
This adds a linter for https://inko-lang.org/, based on the linter for ALE.
> Add a linter for Inko

- README.md
- lua/lint/linters/vint.lua
> Add vint linter

- README.md
- lua/lint/linters/clangtidy.lua
Fixes #25
FYI I'm currently integrating this into [LunarVim](https://github.com/ChristianChiarulli/LunarVim/pull/982)
> [Feature] support clang tidy

- README.md
- lua/lint/linters/eslint.lua
Add eslint support for javascript files
> Configure the eslint parser

- README.md
- lua/lint/linters/nix.lua
- lua/lint/parser.lua
Add a linter for `nix` filetypes.
> Add nix linter

- lua/lint/linters/vale.lua
Fixes https://github.com/mfussenegger/nvim-lint/issues/24
> vale: Map suggestion to Hint

- README.md
- lua/lint/linters/markdownlint.lua
this pull adds a lint configuration for "markdownlint"
> add markdownlint linter

- README.md
- lua/lint.lua
- lua/lint/linters/hadolint.lua
Adds [hadolint](https://github.com/hadolint/hadolint) for linting Dockerfiles
> Add hadolint for Dockerfiles

- lua/lint/linters/vale.lua
- tests/vale_spec.lua
Closes https://github.com/mfussenegger/nvim-lint/issues/45
Closes https://github.com/mfussenegger/nvim-lint/issues/21
> Don't error on empty output in vale parser

- .editorconfig
- .luacheckrc
- README.md
- lua/lint/linters/standardrb.lua
- Add null-ls as alternative to readme
- Add .editorconfig file
- Document how to run tests
> Add null-ls alternative, editorconfig, run tests instructions

- README.md
- lua/lint/linters/stylelint.lua
Adds the CSS linter stylelint.
> Add stylelint

- README.md
Makes it easier to copy paste this block.
> Incredibly impactful README example syntax error fix

- lua/lint.lua
- tests/compiler_spec.lua
See https://github.com/neovim/neovim/pull/15504
> Use new handler signature in nvim 0.5.1+

- lua/lint/linters/rflint.lua
Recently I'm working on a project that uses [Robot Framework](https://robotframework.org/), and I wanted a lint to run in my scripts!
I got [robotframework-lint](https://github.com/boakley/robotframework-lint) to work here and I'm PRing it for anyone else who needs it.
> Add rflint

- lua/lint/linters/jshint.lua
I've got `jshint` to work in my machine, so I decided to PR it!
https://jshint.com/docs/
I have just started using `lua`, so sorry if there are any mistakes!
Thank you for creating this awesome tool! :+1:
> Add jshint

- README.md
> Add rflint and jslint to README

- README.md
- lua/lint/linters/robocop.lua
[Robocop](https://github.com/MarketSquare/robotframework-robocop) is a newer linter for the Robot Framework. Seems to be better than rflint.
PRing it for anyone else who needs it!
> Add robocop

- lua/lint.lua
Fixes https://github.com/mfussenegger/nvim-lint/issues/127
> Ensure linter receives all content before closing stdin

- README.md
- lua/lint/linters/vulture.lua
[Vulture](https://github.com/jendrikseipp/vulture) is the best linter I have found when it comes to finding dead code in Python.
This is my very firest PR in github and totally new to lua/regex, so just tell me if something is wrong or missing :)
Since the arguments of vulture are just a few, this implementation should be robust regardless its input arguments.
> Add vulture

- README.md
- lua/lint/linters/ktlint.lua
Adding the [ktlint](https://github.com/pinterest/ktlint) kotlin linter.
> Add ktlint

- lua/lint/linters/clj-kondo.lua
- lua/lint/linters/golangcilint.lua
- lua/lint/linters/hadolint.lua
- lua/lint/linters/hlint.lua
- lua/lint/linters/inko.lua
- lua/lint/linters/ktlint.lua
- lua/lint/linters/languagetool.lua
- lua/lint/linters/phpcs.lua
- lua/lint/linters/pylint.lua
- lua/lint/linters/selene.lua
- lua/lint/linters/shellcheck.lua
- lua/lint/linters/standardrb.lua
- lua/lint/linters/staticcheck.lua
- lua/lint/linters/stylelint.lua
- lua/lint/linters/vale.lua
- lua/lint/linters/vint.lua
> Replace vim.fn.json_decode calls with vim.json.decode

- lua/lint/linters/pylint.lua
Closes https://github.com/mfussenegger/nvim-lint/issues/190
> Add `fatal` to severity mapping for pylint

- lua/lint/linters/chktex.lua
- lua/lint/linters/selene.lua
- lua/lint/linters/shellcheck.lua
- lua/lint/linters/standardrb.lua
- lua/lint/linters/staticcheck.lua
- lua/lint/linters/stylelint.lua
- lua/lint/parser.lua
- tests/cppcheck_spec.lua
- tests/mlint_spec.lua
- tests/pycodestyle_lint_spec.lua
See https://github.com/neovim/neovim/pull/17510
> Add code as top-level diagnostic property

- lua/lint.lua
> feat(lint) only notify once if possible

- lua/lint/linters/credo.lua
- tests/credo_spec.lua
This is the standard linter used in the elixir community.
> Add credo linter

- lua/lint.lua
Should fix https://github.com/mfussenegger/nvim-lint/issues/215
> Ensure stdout/stderr pipes get closed

- lua/lint/parser.lua
Fixes https://github.com/mfussenegger/nvim-lint/issues/221
> Handle deleted buffer in from_pattern parser

- README.md
- lua/lint/linters/dxc.lua
Seams to work. Will try out for a week or so...
Diff in README is huge because I needed to shift the separator by one space because "DirectX Shader Compiler" was too long.
> feat: add DirectX Shader Compiler

- README.md
Closes https://github.com/mfussenegger/nvim-lint/issues/231
> Mention append_fname in the custom linters readme section

- lua/lint/linters/sqlfluff.lua
- tests/sqlfluff_spec.lua
> add json parser for sqlfluff (fix #210)

- lua/lint/linters/phpcs.lua
Ref: https://github.com/mfussenegger/nvim-lint/issues/242
> feat(phpcs): show error when the output is not json

- lua/lint/linters/checkstyle.lua
- tests/checkstyle_spec.lua
> Change checkstyle error format

- README.md
- lua/lint.lua
- lua/lint/linters/jsonlint.lua
- tests/jsonlint_spec.lua
> feat: add support for jsonlint

- README.md
- lua/lint/linters/luacheck.lua
- lua/lint/parser.lua
luacheck reports end-incluse positions.
Fixes https://github.com/mfussenegger/nvim-lint/issues/260
> Fix luacheck end_col off-by-one error

- README.md
- lua/lint/linters/oelint-adv.lua
- tests/oelint-adv_spec.lua
This PR adds support for the [Bitbake](https://en.wikipedia.org/wiki/BitBake) programming language using the oelint-adv syntax analysis tool.
> [Feature] Add Bitbake/oelint-adv support

- README.md
- lua/lint/linters/psalm.lua
I copied this part of my nvim configuration. Is that everything which is needed? Or do I have to additionally register it somehow?
> Add psalm as linter

- lua/lint/linters/psalm.lua
After trying out the configuration I figured that I was still missing the information diagnostics. Turned out I forgot to include that additional parameter in the PR. Sorry about that!
> Add psalm option to also show infos

- lua/lint.lua
Closes https://github.com/mfussenegger/nvim-lint/issues/272
> Add a `ignore_errors` option to `try_lint`

- README.md
- lua/lint/linters/eslint_d.lua
> Add eslint_d

- README.md
- lua/lint/linters/phpstan.lua
I would like to contribute another linter for PHP. This one does only know about errors and only tell one line, so there is not a lot of information that can be returned. It also does not know about the concept of severity...
> Add phpstan as linter

- README.md
- lua/lint/linters/bean_check.lua
`bean-check` is a syntax checker for Beancount files.
> Add bean_check

- README.md
- lua/lint/linters/verilator.lua
- tests/verilator_spec.lua
Adds support for Verilator Linter!
Closes #295
> Add Verilator

- lua/lint.lua
> bubble up process handle to `try_lint()`

- README.md
- lua/lint/linters/buf_lint.lua
Add support for [buf lint](https://github.com/bufbuild/buf)
> Add buf lint

- README.md
- lua/lint/linters/erb_lint.lua
Add support for Shopify's [erb-lint](https://github.com/Shopify/erb-lint).
> Add erb-lint

- lua/lint/linters/phpmd.lua
- tests/phpmd_spec.lua
Add's support for [PHPMD](https://phpmd.org/).
> Add linter for PHPMD

- README.md
- lua/lint/linters/djlint.lua
Greetings,
I have kept an eye on this project since I got to know that null-ls is going to be archived. I decided to add support for DjLint (although I couldn't test it, because it seems my environment doesn't currently allow me to use `try_lint` and have the results published in the diagnostic list).
This hopefully helps with #236 
Thank you for your attention!
> Added djlint support

- README.md
- lua/lint/linters/solhint.lua
This is an adapted version of #197, I adapted the code to the new repo style.
> Add solhint

- lua/lint/linters/gdlint.lua
https://github.com/mfussenegger/nvim-lint/pull/349#issuecomment-1690285326
> Map gdlint errors to warning

- lua/lint/linters/twigcs.lua
- tests/twigcs_spec.lua
Add [twigcs](https://github.com/friendsoftwig/twigcs) lint configuration to nvim-lint for use with twig files.
> Add Twigcs lint configuration

- lua/lint/linters/selene.lua
* ✔ fixed reporting location
* ✔ added support for stdin
> fix: selene linter

- README.md
- lua/lint/linters/deno.lua
- lua/lint/linters/deno_lint.lua
add `deno_lint` option to use the linter from deno.
> Add Deno lint support

- README.md
- lua/lint/linters/standardjs.lua
> Support standardjs

- README.md
- lua/lint/linters/biomejs.lua
> Add biomejs

- lua/lint/linters/eslint.lua
- lua/lint/linters/eslint_d.lua
- tests/eslint_d_spec.lua
👋🏼 ,
This PR aims to repair the ESLint issues introduced with https://github.com/mfussenegger/nvim-lint/pull/409, which I apparently didn't validate good enough...
The mocked test JSON should now be correct and the parser correctly picks the first item from the output, which is exactly how `null-ls` has handled it.  
Sorry for the introduced issue... 😮‍💨
> fix: repair eslint linters

- lua/lint/linters/eslint.lua
- lua/lint/linters/eslint_d.lua
- tests/eslint_d_spec.lua
> Revert broken eslint changes

- README.md
- lua/lint/linters/write_good.lua
this pr adds the write-good linter
> adding write-good linter

- README.md
- lua/lint/linters/commitlint.lua
- tests/commitlint_spec.lua
> feat(commitlint): add commitlint linter

- README.md
- lua/lint/linters/snyk_iac.lua
- tests/snyk_iac_spec.lua
> feat(snyk): add snyk linter

- lua/lint/linters/cmakelint.lua
> fix cmakelint error on windows

- README.md
Closes https://github.com/mfussenegger/nvim-lint/issues/363
> Update motivation & goals prose

- README.md
fixes #458 Added existing fish linter to README.
> chore: add fish to README

- lua/lint.lua
- lua/lint/linters/cpplint.lua
- lua/lint/linters/cspell.lua
- lua/lint/linters/eslint.lua
- lua/lint/linters/eslint_d.lua
- lua/lint/linters/shellcheck.lua
- lua/lint/linters/stylelint.lua
- lua/lint/util.lua
Alternative for:
- https://github.com/mfussenegger/nvim-lint/pull/471
- https://github.com/mfussenegger/nvim-lint/pull/473
> Always spawn linter via cmd.exe on windows

- README.md
- lua/lint.lua
Hi, 
I'd like to see which linters are currently running. This seemed like a very straightforward implementation.
I'm still fairly new to plugin development and Lua, so there might be some obvious improvements possible.
#366
> feat(running linters): see the running linters for a  buffer

- README.md
- lua/lint/linters/joker.lua
joker is a small clojure interpreter, formatter and linter.
> Add joker (clojure linter)

- README.md
- lua/lint.lua
Closes https://github.com/mfussenegger/nvim-lint/issues/485
> Add function to get namespace for per linter display-config

- README.md
- lua/lint/linters/opa_check.lua
- lua/lint/linters/regal.lua
https://github.com/mfussenegger/nvim-lint/pull/504 with conflicts fixed
> Add regal and opa_check

- lua/lint/linters/sqlfluff.lua
> sqlfluff: change default dialect to ansi

- README.md
- lua/lint/linters/cue.lua
adding new linter for the CUE language using the `cue vet` command
> feature: add CUE linter

- README.md
- lua/lint/linters/swiftlint.lua
- tests/swiftlint_spec.lua
I've been using this configuration for some time, but I decided that it would be nice for others to have it built-in here :)
> Add swiftlint support

- README.md
- lua/lint/linters/deadnix.lua
- tests/deadnix_spec.lua
I wrote this configuration with inspire of already in-built and from GitHub code.
> Add deadnix support

- lua/lint/linters/phpstan.lua
- tests/phpstan_spec.lua
* tries to fix https://github.com/mfussenegger/nvim-lint/issues/581
* adds a test for phpstan
> fix phpstan baseline error

- README.md
- lua/lint/linters/oxlint.lua
> feat: add oxlint, the faster eslint alternative

- README.md
- lua/lint/linters/protolint.lua
Hi @mfussenegger and thanks for this the awesome nvim-lint project! 👋 
Here's a simple but functioning implementation for [protolint](https://github.com/yoheimuta/protolint). 😄 
This is how I've implemented it locally, and which shows warnings just fine: https://github.com/fredrikaverpil/dotfiles/commit/44fe5b5e560077764a2b2f78b9ca33591f489e24
> Add Protolint

- README.md
- lua/lint/linters/ameba.lua
- tests/ameba_spec.lua
The PR brings support for a Crystal language linter [ameba](https://github.com/crystal-ameba/ameba)
> Add ameba linter

- README.md
- lua/lint/linters/clippy.lua
Rust linting using cargo clippy, done to the best of my limited abilities. Since clippy lints the whole project, some filtering has to be done. I am not too keen on the recursion but sometimes there is useful information from the child messages. Thanks!
> feat: add clippy

- lua/lint/linters/tidy.lua
tidy exits with exit code 1 if any issues are reported
> tidy: Set ignore_exitcode

- lua/lint/parser.lua
Problem:
People tend to use functions like `vim.fn.expand("%:p")` in PRs which
would be broken because the parse function is called asynchronous after
the linter process finished and in the meantime the user could've
switched buffers.
Solution:
Use `nvim_buf_call` to ensure the parse function is run in the
context of the original buffer.
> Ensure parse functions run in the context of the original buffer

- doc/lint.txt
- lua/lint.lua
- lua/lint/parser.lua
Alo changes the order of some functions to ensure the more important
ones appear first in the docs.
> Add API docs generated using vimcats

- README.md
- lua/lint/linters/yq.lua
This pr adds support for [yq](https://github.com/mikefarah/yq). It can be used with quite a few file types like YAML, JSON and XML. Let me know what you think.
> Add yq linter

- README.md
- lua/lint/linters/bash.lua
- lua/lint/linters/ksh.lua
- lua/lint/linters/luac.lua
I put each linter in its own commit so that it is easy to bisect the history and/or revert them individually.
> Add luac, ksh, and bash linters

- README.md
- lua/lint/linters/snakemake.lua
- tests/snakemake_spec.lua
Adds support for [snakemake](https://snakemake.github.io)'s built-in linter.
> Add snakemake linter

- README.md
- lua/lint/linters/rpmlint.lua
- spec/rpmlint_spec.lua
> Add rpmlint

- lua/lint/linters/standardjs.lua
Implemented same pattern used for Eslint to detect linter binary. Solves #519
> refactor(standard): Use Eslint pattern to detect binary

- README.md
- lua/lint/linters/zizmor.lua
This PR adds builtin support for [`zizmor`](https://github.com/woodruffw/zizmor), a static analysis tool for GitHub Actions.
> feat(zizmor): Add zizmor linter

- lua/lint/linters/jq.lua
Closes https://github.com/mfussenegger/nvim-lint/issues/651
> jq: Allow trailing whitespace

- lua/lint/linters/mypy.lua
> chore: remove mypy hardcoded executable

- README.md
- lua/lint/linters/fortitude.lua
- spec/fortitude_spec.lua
Added a linter for fortitude.
I am not sure if the test is necessary as it is incredibly basic, but now it there.
Let me know if I can improve it.
> feat: add support for fortitude

- lua/lint/linters/golangcilint.lua
> fix: update golangci-lint configuration for v2

- lua/lint/linters/phpcs.lua
- spec/phpcs_spec.lua
You can find all the context here: https://github.com/mfussenegger/nvim-lint/issues/794
> 794 Adding support for --stdin-path option to phpcs

- README.md
- lua/lint/linters/fsharplint.lua
https://github.com/fsprojects/FSharpLint
> feat: support fsharplint
