mfussenegger/nvim-lint

README.md, lua/lint/linters/shellcheck.lua
This PR adds ShellCheck to the list of available linters
The JSON object also has a `fix` key that contains the information necessary to do automatic fixes but AFAIK there's no way to configure client-side code actions.
Thanks for the cool plugin! Works really well :)
=> Add ShellCheck

README.md
Should be fixed in the Github project description, too.
=> Grammar fix a -> an in README

README.md, lua/lint/linters/mypy.lua
Hello, awesome plugin. I was messing around with it and added the two linters: `mypy` and `flake8` for Python files. I will submit another PR for `flake8`.
`mypy` does not have the support to take input from stdin and so we have to use pattern matching to extract the out information from the output. I added a helper function `split` which can help in that. I put it in the `util` module as I believe it could be useful for other linters as well.
=> feat: Add Mypy linter

README.md, lua/lint/linters/tidy.lua
This PR adds HTML Tidy to the list of available linters
Since Tidy only reports a line and a column number, I chose to leave an offset of 1 like in #7
=> Add HTML Tidy

README.md, lua/lint/linters/flake8.lua
As mentioned in my previous pull request, adding the `flake8` linter configuration for Python files.
`flake8` does take input from stdin but when I tried to configure it as such it was giving me false-positives. I tried running `flake8` directly from the command line and it was not giving me those errors there. There seems to be some issue as to how this plugin works with stdin linters.
**Conditions tested on:**
- Running only `flake8` for Python file in neovim using `nvim-lint` (gives false-positive)
- Running `flake8` from command line (does not give false-positive)
- Running `flake8` from command line through stdin (`cat <file> | flake8 -`) (does not give false-positive)
- Running `flake8` from neovim command prompt (`:%!flake8 -`) (does not give false-positive)
Also, `flake8` has its …
=> feat: Add Flake8 linter

lua/lint/linters/staticcheck.lua
This still has two problems:
1. Just like the `shellcheck` linter, there is the message "Linter exited with code 1" after linting, even though it seems to work correctly.
1. It currently fails, unless I hardcode the values for end line/character, with
> Linter definition must have a `cmd` set: "vim.lua:129: .../packer/start/nvim-lint/lua/lint/linters/staticcheck.lua:25: '<name>' expected near 'end'
I guess that has to do with the keyword `end` in the json output.
Edit: Fixed issue two by reading more lua documentation.
=> Add staticcheck linter for go

README.md, lua/lint.lua, lua/lint/linters/shellcheck.lua, lua/lint/linters/staticcheck.lua
Set to true for shellcheck and staticcheck.
As mentioned in https://github.com/mfussenegger/nvim-lint/pull/11.
=> Add linter property to ignore the exit code

lua/lint/linters/mypy.lua
This ensure a consistent output from Mypy regardless of what might be in a project's `mypy.ini` (or similar) that could alter the output format causing parsing errors.
It also removes the need for removing the "found n errors... / Success: no issues ..." message because it's not printed to begin with.
=> Ensure consistent Mypy output regardless of project configuration

lua/lint/linters/flake8.lua
Similar to GH-14. Without this the output can be changed by local configuration files causing output parsing to fail.
=> Ensure consistent Flake8 output formatting

lua/lint/linters/pylint.lua
Pylint returns a column of 0 for convention lint messages. For this the
substraction of 1 was removed so that using
`vim.lsp.diagnostic.goto_next` causes no problems.
=> Add pylint

README.md, lua/lint/linters/golangcilint.lua
Add `golangci-lint` linter. [golangci-lint](https://golangci-lint.run/) is a linter for Go that aggregate other popular Go linter together in one tool.
=> Add golangci-lint linter

lua/lint.lua, lua/lint/linters/ruby.lua
This linter uses Ruby's built-in syntax checking option. In addition, we
make this linter the default linter to run for Ruby files.
=> Add linter for Ruby

lua/lint/linters/golangcilint.lua
Hello! I Great idea btw to wire the linters to the lsp handlers 🎉 !  
I  spotted 👇  while giving it a try for Go, so here is a fix. 
If no path is passed to golangci-lint, it will run on the current
folder, yielding many different diagnostics which are not related to the
current file.
The problem is that those are still going to be displayed on the current
buffer, using their position in their files. This lead to a meaningless
superposition of all diagnostics on the current file.
Forcing Golangci to run only on the current file will yield false positives, because some symbols will be missing for the linters to parse. So, this code just throw away the diagnostics that do not concern the current file. 
That's rather crude, but it works.
=> Tell golangci to use the current buffer only

lua/lint/linters/revive.lua, lua/lint/parser.lua
`./path/to/file/main.go:15:2: don't use ALL_CAPS in Go names; use CamelCase` This error was causing the pattern matching for revive to fail.
=> Fixed golang revive linters matching pattern

README.md, lua/lint/linters/cppcheck.lua
This PR adds initial, somewhat hacky support for [cppcheck](http://cppcheck.sourceforge.net/).
The hacky parts are:
1. It currently hardcodes the presence of a build directory named `build` and a `compile_commands.json` in that directory.
2. It runs `cppcheck` on the whole project and filters out diagnostics relevant to the current file.
3. It probably doesn't work right if a file has been modified but not saved.
This is very similar to the approach `ALE` takes, but I think we could do better by (1) more robust `compile_commands.json` detection and (2) maybe somehow parsing compile args from `compile_commands.json` ourselves to allow only running `cppcheck` on the currently relevant file (the tool is obnoxious and will either run on the whole project with compile args from a …
=> Feature: Add cppcheck support

README.md, lua/lint/linters/luacheck.lua
This PR adds [luacheck](https://github.com/mpeterv/luacheck) as a builtin linter for Lua.
=> Add luacheck support

README.md, lua/lint/linters/chktex.lua
This PR adds [chktex](https://www.nongnu.org/chktex) as a builtin linter for TeX files.
=> Add chktex linter

README.md, lua/lint/linters/chktex.lua, lua/lint/linters/clangtidy.lua, lua/lint/linters/cppcheck.lua, lua/lint/linters/flake8.lua, lua/lint/linters/luacheck.lua, lua/lint/linters/mypy.lua, lua/lint/linters/revive.lua, lua/lint/linters/ruby.lua, lua/lint/linters/tidy.lua, lua/lint/parser.lua
Hello,
I'd like to propose a change to the method named `from_pattern`, because it has a big impact I only recoded the function and will wait for your approval before going on.
The motivation is to support all the [Diagnostic](https://github.com/mfussenegger/nvim-lint#from_pattern) attributes and to make the parser flexible regarding what groups will be parsed using the regex.
This also allows adding new diagnostic fields in the future without worrying about refactoring.
Finally, I like the more concise and explicit definition of the parsers, for instance, I tested with cppcheck which could be defined as follows:
```
local pattern = [[([^:]*):(%d*):(%d*): %[([^%]\]*)%] ([^:]*): (.*)]]
local groups = {"file", "lineno", "colno", "code", "severity", "message" }
local severity_map = { …
```
=> Refactor from_pattern

README.md, lua/lint.lua, lua/lint/linters/clj-kondo.lua
- Adds [clj-kondo](https://github.com/clj-kondo/clj-kondo) as a linter for clojure and clojurescript files
=> Add clj-kondo for Clojure(script)

README.md, lua/lint/linters/standardrb.lua
This adds the ruby linter for standardrb.
This ends up looking like this
I was hoping that by returning the code that it would show up somehow, but I don’t see how to get at it. I was wondering if I should prepend it like this instead?
It's useful to know the name you want to disable that check.
=> Add StandardRB

lua/lint/linters/clj-kondo.lua
Based on feedback from the author @borkdude:
- Removed the --parallel option as it performs better on multiple files
than one buffer which is the case here.
- Pass the file name from the buffer to help clj-kondo determine the
type(clj, cljs, cljc, edn) better
=> Improve clj-kondo setup

lua/lint/parser.lua
The defaults table was not used at all because the loop would iterate
over only those keys present in the `group_handler` table.
An example would be `flake8` where the defaults contain the `source` key
but it is ignored as that key is absent from the `group_handler` table.
Solution:
Merge the diagnostic table with the defaults table after constructing
the diagnostic table as per the linter output.
=> fix: use values from the defaults table

lua/lint/linters/cppcheck.lua
Closes https://github.com/mfussenegger/nvim-lint/issues/46
=> Remove `--project=` option for cppcheck

lua/lint/linters/flake8.lua
flake8 returns an exit code of 1 when it finds errors, which should be
ignored.
=> flake8: ignore exit code

lua/lint/linters/mypy.lua, lua/lint/parser.lua
Linters output path relative to the project root and so we should
compare against that.
I noticed this with `mypy` where it would not send the diagnostics to the client as the path would differ.
Edit: Also, `mypy` exits with code 1, so I think we should ignore it by default similar to `flake8`
=> fix: compare path relative to project root

lua/lint/linters/flake8.lua
Since the overwhelming majority (maybe all?) of the "errors" that flake8 emits are, in fact, style/lint warnings, it makes more sense to default to using Warning as the default severity rather than Error.
=> flake8: use Warning as default severity

lua/lint/linters/luacheck.lua
There is some weird bug where luacheck will report EOF errors in the
middle of the file.
I managed to avoid the error if the `stdin:write` calls get throttled -
but that's not an acceptable fix within nvim-lint.
I'm not sure if this is some luv related bug, or if the problem is on
the luacheck side.
This disables the stdin support for now to get it working.
=> Disable stdin for luacheck

lua/lint/linters/markdownlint.lua, tests/markdownlint_spec.lua
Fixes https://github.com/mfussenegger/nvim-lint/issues/70
=> markdownlint: Support both lines with column info and without

.github/workflows/linter.yml, .luacheckrc, README.md, lua/lint.lua, lua/lint/linters/compiler.lua, lua/lint/parser.lua, tests/both.py, tests/compiler_spec.lua
See commits
Replaces https://github.com/mfussenegger/nvim-lint/pull/77
Fixes https://github.com/mfussenegger/nvim-lint/issues/73
=> Support stdout/stderr output and global efm/makeprg in compiler linter

lua/lint/linters/luacheck.lua
This reverts commit 84261b62e0d1b3182daf7ae7d4fcfa71148b37b0.
Root cause of the issue was fixed with 359aa4fe3414da6a7abb9154b5b62bd2508748e6
=> Revert "Disable stdin for luacheck"

lua/lint/linters/fennel.lua
This lets us capture the column of the error from the ^^^ characters (`%p` in `'errorformat'`).
I spent way too long on this...
=> fennel: update 'errorformat'

lua/lint/linters/eslint.lua
Punctuation in error messages is now captured properly, which prevents some error messages from getting cut off or left out completely.
Addresses #69 and #92.
=> More effective eslint capture groups

lua/lint/linters/cppcheck.lua, lua/lint/parser.lua, tests/cppcheck_spec.lua
Allow parser to parse `{column}` or the actual column number. Default
column to 1.
Addresses #87
=> Add backwards compatibility to cppcheck 1.34

lua/lint/linters/eslint.lua
This is a follow up to #93, further refining the 'message' capture group in the eslint pattern. This prevents trailing spaces from getting captured in the diagnostics messages.
=> 'message' group no longer captures trailing spaces in eslint pattern

lua/lint.lua, tests/compiler_spec.lua
Latest neovim master finally uses the LSP `client` in the diagnostic
publish path, so the faked CLIENT_ID no longer works.
This adds a compat layer to use the vim.diagnostic API.
This is only a intermediate solution. Once 0.6 is released, nvim-lint
will drop support for 0.5 and fully embrace the vim.diagnostic API.
(Meaning all parsers will have to return the vim.diagnostic item format)
Side effect of this change is that if you're on master you need to use `vim.diagnostic.config` to configure how the diagnostics are displayed instead of relying on the publishDiagnostics handler customization.
=> Use vim.diagnostic to publish diagnostics

README.md, lua/lint/linters/statix.lua
Add the statix linting and suggestion tool for the Nix programming
language to both the linter configs and the list of available linters.
It uses errorformat, so it was really easy to write, and last I saw it
worked properly and found some issues with my dotfiles' flake.nix
file, defined manually and by using this fork.
Let me know if I should add a test or something. I'm just not sure
what I'd test.
=> Add Statix

README.md, lua/lint/linters/flawfinder.lua
Add support for flawfinder, a CWE enumeration tool for C/C++. 
Took me a couple of tries to figure out `from_pattern` since I didn't know Lua uses percent-signs for their regex escape character.
=> Add flawfinder

lua/lint/linters/statix.lua
With the update to v0.4.0, statix introduced an "--stdin" flag, so this
linter can now support processing buffers, as well as a breaking change
of moving the lint output from stderr to stdout.
=> Update statix for v0.4.0

README.md, lua/lint/linters/cspell.lua, tests/cspell_spec.lua
Implement the `cspell` linter, one of the most popular extensions for VSCode.
Signed-off-by: David Houston <houstdav000@gmail.com>
=> Add cspell Linter

lua/lint/linters/pylint.lua, tests/pylint_spec.lua
Pylint's parser function signature doesn't match the expected, so it's failing. Add logic for handling files from the `from_pattern` method to compensate.
Closes #115
=> Fix pylint to run successfully

lua/lint.lua
If one sets up a linter for temporary buffers like the gitcommit buffer
from fugitive, a `:wq` can trigger the linter but by the time the result
is ready the buffer will be gone.
This caused an error that the buffer isn't valid in
`vim.diagnostic.set`.
=> Ignore diagnostics for deleted buffers

README.md, lua/lint/linters/pydocstyle.lua, lua/lint/parser.lua, tests/minimal.vim, tests/parser_spec.lua, tests/pydocstyle_spec.lua
__NOTES:__
- The pydocstyle config has the multi-line errorformat situation described in #125 and therefore it will benefit from the included fix for it. 
- The rtp fix is something I noticed after a long while having the test suite failing doing this PR before discovering the problem in the test setup.
- See extended commit messages for specific detail on each commit
=> Fix #125, Fix incorrect testing rtp, and add pydocstyle linter config

lua/lint/linters/golangcilint.lua
golangci-lint is a meta linter composing a number of other popular
linters according the config it reads. It is often helpful to know
exactly which linter produced a diagnostic. In fact, when run on the
command line, the tool prints the linter name by default.
This change updates the format of the diagnostic message to include the
linter. Note that while golangci-lint accepts
`--print-linter-name=false`, this setting appears to be ignored when
`-out-format json` is set.
-------------------------------------------
PR note: I am not sure if you accept contributions like this but I figured it was worth a shot. It is simple enough to override my parser locally, but I figured that in this case it may be worth updating the message to a sensible (in my opinion) default. No offense taken if you …
=> golangci-lint: add FromLinter to diagnostic

lua/lint.lua
Fixes a regression introduced with https://github.com/mfussenegger/nvim-lint/commit/cc6b0f3ce3037a01fb371f502ba5f6301cb7f0a2
=> Fix `expected table, got nil` error if there are no linters for a filetype

lua/lint/linters/selene.lua
selene uses severity levels like "Error", while nvim expects "ERROR"
=> severity matching for selene

lua/lint/linters/selene.lua
warning also doesn't work, so a mapping is required
=> selene further improvements

lua/lint.lua
Fixes https://github.com/mfussenegger/nvim-lint/issues/144
Let's hope that's still good enough to keep
https://github.com/mfussenegger/nvim-lint/issues/131 closed.
=> Flush stdin without extra newline

README.md, lua/lint/linters/cpplint.lua
New lint added. This static code checker ([repo here](https://github.com/cpplint/cpplint)) is checks that C++ code conforms the C++ google guidelines. Lightweight and fast one. Output example after executing the command:
```
src/file.cpp:78:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
src/file.cpp:79:  Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
```
=> feat: add cpplint

README.md, lua/lint/linters/proselint.lua
Linter based on the grammar aspect! Expected cli output is the following one:
```
doc/dev/filename.rst:108:69: after_the_deadline.redundancy Redundancy. Use 'same' instead of 'same exact'.
doc/dev/filename.rst:147:33: typography.symbols.curly_quotes Use curly quotes “”, not straight quotes "".
doc/dev/filename.rst:151:33: typography.symbols.curly_quotes Use curly quotes “”, not straight quotes "".
```
I will be updating with a few different ones later :)
=> feat: add proselint

README.md, lua/lint/linters/cmakelint.lua
[CMake linter](https://github.com/cmake-lint/cmake-lint). This one mainly checks format. I would like to add the one provided by the cmakelang ([cmake-lint](https://pypi.org/project/cmakelang/)). Although the have quite similar names, the first one (this one) checks for style and the other one seems to check for error/warnings in the code. CLI Output of the one from this PR:
```
conan.cmake:399: Extra spaces between 'foreach' and its () [whitespace/extra]
conan.cmake:400: Lines should be <= 80 characters long [linelength]
```
=> feat: add cmakelint

README.md, lua/lint/linters/rstcheck.lua
More linters I added. This time the first rst check as far as I know :) 
Link: [rstcheck](https://github.com/myint/rstcheck)
CLI output example:
```
doc/test_file.rst:87: (WARNING/2) Title underline too short.
```
=> feat: add rstcheck

README.md, lua/lint/linters/rstlint.lua
New linter: [restructuredtext-lint](https://github.com/twolfson/restructuredtext-lint)
It can be launched eitther with `rst-lint` or `restructuredtext-lint`. If the naming leads to confusion I can change also them. Example output:
```
ERROR doc/dev/example.rst:94 Unknown interpreted text role "ref".
```
=> feat: add rstlint

lua/lint.lua, tests/lint_spec.lua
Add a fallback in case there is no entry for the full compound filetype
definition.
A filetype like `ansible.yaml` will first look for an `ansible.yaml`
entry and if it doesn't exist it will lookup both `ansible` and `yaml`
and merge the found linter names.
Closes https://github.com/mfussenegger/nvim-lint/issues/141
=> Lookup linters for individual filetype on compound filetype

tests/mlint_spec.lua, tests/pycodestyle_lint_spec.lua
Tests started to fail after https://github.com/neovim/neovim/pull/16745
because the tests didn't provide the buffer number to the parse
function.
=> Fix "Expected Lua number" test failures

lua/lint/linters/vulture.lua
The idea of this PR is to improve the scope of Vulture (dead code and unused variables analyzer). By default, the filename is passed as argument, which prevents the linter to analyze the full context of an entire repository. This leads to lots of false positives. The current implementation uses as input argument the git root directory if exists or the current dir otherwise. Tested both of them and works fine.
Fixes #153
=> fix: improve vulture scope

lua/lint/linters/codespell.lua, lua/lint/linters/pylint.lua, tests/pylint_spec.lua
Just a small PR. Since I use Trouble to look at the diagnostics, I could not see some of the information that some linters are supposed to retrieve.
I guess that the previous implementation of Pylint did not read the `message-id` because it was not possible. It seems that, in order to read a value from a lua table, all the keys have to be valid identifiers (which means no hyphens are allowed). Due to this I replaced `message-id`by `message_id`. Thanks to it it was possible to be read.
There might be more linters without this info, but I do not want to modify those that I cannot test. These are the oens I verified:
```  
python = {'flake8', 'mypy', 'pylint', 'vulture', 'codespell', 'pytestcov'},
cpp = {'cppcheck', 'clangtidy', 'cpplint', 'codespell'},
rst = {'rstlint', 'rstcheck', …
```
=> fix: better information retrieved pylint and codespell

README.md, lua/lint/linters/phpcs.lua, tests/phpcs_spec.lua
First - thanks for this plugin! Switched over from `ale` recently and am loving the speed this plugin has.
Was in need of a `phpcs` lint integration, so I wrote my own. This integration works locally, but this is my first time writing Lua so am happy to implement any suggestions 😄
Edit: Looks like the Github Actions won't run automatically, but I did run the tests I added locally and they did pass.
=> Add phpcs linter

lua/lint/linters/golangcilint.lua
Current configuration for `golangci-lint` doesn't seem work, since reading file content from STDIN is not supported.
Set `append_fname` to true so that the command would look like
```
golangci-lint --output-format=json <current-filename>
```
This is fix to #167
=> Read file content instead expecting input from stdin.

lua/lint/linters/golangcilint.lua
Appending files means that some linters consider only the contents of the given file when linting it. This is a problem as those linters will not be able to find symbols defined in other files in the same package. `typecheck` is the easiest linter to verify as it will claim that types defined on other files couldn't be found.
=> golangci-lint: appending file breaks some linters

lua/lint/linters/golangcilint.lua
Some of the linters available with golangci-lint return 0 as a column
value if the issue affects the whole line. The golangci-lint integration
in nvim-lint then subtracts 1, which leads to a negative number.
Newer versions of Neovim treat this as invalid. The result is an error
when trying to jump to that line using `vim.diagnostic.goto_next()`.
This commit ensures that any column or line numbers always remain >= 0.
Closes #176
=> Ensure column and line numbers remain >= 0

lua/lint/linters/vale.lua
Made a quick fix for #186, hope it helps. No multi-line support, because I think Vale doesn't output multi-line errors.
=> Quick fix for incorrect highlighting with Vale linter

README.md, lua/lint/linters/lacheck.lua
Create a new linter that parses the outputs of lacheck, a linter for
LaTeX files. This linter only returns line number and a message through
stdout by passing the .tex file as input. lacheck is not capable of
getting the input through stdin.
=> Add linter for lacheck

README.md, lua/lint/linters/glslc.lua
WIP: because this linter requires a output file. Also it can only guess the type of the shader when shader has typical file extension like `*.vert` `*.frag` or a pragma in the shader (https://github.com/google/shaderc/tree/main/glslc#311-shader-stage-specification)
=> feat: add glslc

lua/lint/linters/ruby.lua, tests/ruby_spec.lua
Since the execution of ruby linter fails due to the breaking change of Neovim 0.7, I made it explicit to pass `bufnr` as an argument.
When I run ruby linter with nvim-lint plugin on Neovim 0.7, I get the following error:
```
Error executing vim.schedule lua callback: .../.local/share/nvim/plugged/nvim-lint/lua/lint/parser.lua:89: Expected Lua number
stack traceback:
[C]: in function 'nvim_buf_get_name'
.../.local/share/nvim/plugged/nvim-lint/lua/lint/parser.lua:89: in function 'parser'
...l/share/nvim/plugged/nvim-lint/lua/lint/linters/ruby.lua:31: in function 'parse'
.../.local/share/nvim/plugged/nvim-lint/lua/lint/parser.lua:110: in function <.../.local/share/nvim/plugged/nvim-lint/lua/lint/parser.lua:108>
```
In Neovim 0.7, when passing `nil` to `nvim_buf_get_name`, it no longer …
=> ruby: Do not pass nil to nvim_buf_get_name

lua/lint/parser.lua
`:h errorformat` doesn't indicate a preference/requirement for capital-letter error types:
```
%t		error type (finds a single character):
e - error message
w - warning message
i - info message
n - note message
```
This ended up being relevant to a linter I was developing, so I thought I would submit this trivial fix.
=> Case-insensitive severity value in `from_errorformat()`

lua/lint/linters/pylint.lua
In some python files I was getting this error:
```
Error executing vim.schedule lua callback: ...vim/site/pack/all/start/lint/lua/lint/linters/pylint.lua:32: missing mapping for severity info
stack traceback:
[C]: in function 'assert'
...vim/site/pack/all/start/lint/lua/lint/linters/pylint.lua:32: in function 'parse'
.../share/nvim/site/pack/all/start/lint/lua/lint/parser.lua:110: in function <.../share/nvim/site/pack/all/start/lint/lua/lint/parser.lua:108>
```
Fixed it locally by adding the `info` severity.
Checked the man page for the `info` severity but didn't find any, but I found [in the online documentation](https://pylint.pycqa.org/en/latest/user_guide/messages/messages_overview.html#information-category).
My pylint version (under Arch Linux):
```
> pylint --version
pylint 2.13.8 …
```
=> Fix pylint: missing mapping for severity info

README.md, lua/lint/linters/rubocop.lua, tests/rubocop_spec.lua
This PR adds [RuboCop](https://github.com/rubocop/rubocop) linter for Ruby codes.
=> feat: add rubocop linter

lua/lint/linters/hlint.lua
=> Fix #225: hlint fails with non-zero exit-code unless there are no hints

README.md
It's easier to setup a global autocmd instead of one per buffer.
If people copy the example verbatim into their `init.vim` without
knowing what `<buffer>` is for they may get the impression that it
doesn't work.
`try_lint` uses the registered linters (`linters_by_ft` anyways)
=> Remove <buffer> from autocmd example in README

lua/lint/linters/lint-openapi.lua
Added support for [IBM OpenAPI validator](https://github.com/IBM/openapi-validator).
By default `lint-openapi` output separate lists of error and warning messages, so theres' two `for` loops (for each list). Only Errors and Warnings will be displayed for now.
`lint-openapi` cannot handle `\` or `\\` in file paths, so I had to add a function to replace `\` to `/`.
=> Added `lint-openapi`

lua/lint/parser.lua
Some parsers try to access the buffer but fail if it got deleted
in-between. Skipping the parse step saves some CPU cycles and prevents
the errors. The result would be discarded anyways.
=> Skip parsing result if the buffer is no longer valid

lua/lint/linters/pylint.lua, tests/pylint_spec.lua
I noticed it didn't have any underline/undercurl etc for pylint. This should fix it.
First I tried to just add the end_column, but noticed the starting column was one off.
=> Fix column for pylint

lua/lint/linters/sqlfluff.lua, tests/sqlfluff_spec.lua
when there's a problem running `sqlfluff` _that is not from the input file_ the command will print a non-json text. 
This PR takes care of such problems. The message is reported as "the linter found a problem in the first line-col"
=> sqlfluff: handle non-json output 

lua/lint.lua, lua/lint/parser.lua, tests/parser_spec.lua
=> feat: allow to set cwd

README.md
In my original PR I accidentally put `Tcl` instead of `Nagelfar` for the tool name. This commit corrects that error.
=> docs: update README to fix typo

lua/lint/linters/rubocop.lua, tests/rubocop_spec.lua
The RuboCop linter's JSON output will always have a "files" key with a list of linted files. nvim-lint looks for the first of these files with `decoded.files[1]`.
Given that nvim-lint passes `--force-exclusion` to the `rubocop` binary, it's entirely possible that the "files" value in the JSON data will be an empty array (`[]`).
With this change, the nvim-lint processing of the RuboCop results will prevent an error by not attempting to access an entry in the "files" array that is not there.
A new test has been added to demonstrate the problem and confirm the fix.
Future ideas:
- make the `--force-exclusion` flag optional
- alert the NeoVim user that the file for the current buffer was excluded, lest they believe that the linter processed the file without finding any issues
=> rubocop: handle empty files list being returned

tests/compiler_spec.lua
Can interfere with lua-language-server analysis, leading to wrong hover
and signature information.
=> Remove diagnostic.set override from test

lua/lint/linters/pylint.lua, tests/pylint_spec.lua
The value can be used when rendering diagnostic information. For example, it is used by default in the diagnostic float window since https://github.com/neovim/neovim/pull/21130.
c.f. `:help diagnostic-structure`
=> Add code field to Pylint's diagnostics

lua/lint/linters/cspell.lua
Not sure if `cspell` changed behavior or if I just missed this when adding the linter. Either way, this should be all that's needed to fix.
=> cspell: Ignore normal error code

README.md, tests/both.py, tests/compiler_spec.lua
Use path resolution to allow for testing on systems that may not have `/usr/bin/python` as the path for Python 3. Additionally, alter `both.py` shebang to match.
Added notice of Python test dependency to the README section.
I specifically use NixOS which does not store binaries in `/usr/bin` or `/bin`, and so had this test fail without this fix. Either way, the resolution system in both the `makeprg` variable and the `both.py` shebang should be the same -- absolute or via PATH.
=> tests/compiler_spec: Make Python bin relative

lua/lint/linters/ruff.lua
Allows it to give more accurate results.
Eg there's a lint for "this file has a shebang but is not executable", giving ruff the filename allows it to tell whether the file is executable or not.
=> provide filename to ruff

lua/lint/linters/statix.lua
`statix` returns a non-zero exitcode if the checked file (or buffer) contains any errors.
=> fix: statix returns a non-zero exitcode if there are any errors

lua/lint/linters/stylelint.lua
Same as for ESLint: first try to find stylelint in node_modules binaries, fallback to system stylelint
=> Find stylelint in node_modules binaries first

lua/lint/linters/stylelint.lua
This way it respects stylelint's file based overrides [^1].
[^1]: https://stylelint.io/user-guide/configure/#overrides
=> Add fname as an argument to stylelint

lua/lint/linters/psalm.lua
Prefer a local installation as some other linter configs already do.
Psalm can also be installed as a phar, so I added a check for this as well.
=> psalm: Prefer `./vendor/bin/psalm`

lua/lint/linters/hlint.lua, tests/hlint_spec.lua
The current implementation only shows the summary for hlint.
This adds the suggested change to the diagnostic message.
Before:
```haskell
concat $ map escapeC s -- Use concatMap
```
After:
```haskell
concat $ map escapeC s -- Use concatMap: concatMap escapeC s
```
=> hlint: add suggested change to message

README.md, lua/lint/linters/checkpatch.lua, tests/checkpatch_spec.lua
As described in checkpatch.lua, the user either needs to adjust cmd from its config to provide a full path to checkpatch.pl, or checkpatch.pl should be available in the PATH.
=> Add Linux kernel's checkpatch.pl support

lua/lint/linters/ruff.lua
I recently encountered a project whose ruff configuration sets the `fix` option.  That's all very well when running from the command line - and `ruff --fix --stdin-filename % -` makes a fine `formatprg` - but it's not what's wanted here.
The result is that the buffer contents are sent through ruff, which fixes them, and reports no errors.
Add `--no-fix` to the command line to solve this.
=> Add --no-fix to ruff command line

lua/lint/linters/eslint.lua, lua/lint/linters/eslint_d.lua, lua/lint/linters/stylelint.lua, lua/lint/util.lua
Problem
====
On Windows, some linters are installed with the shim command suffixed with ".cmd" to run by its interpreter programs (such as Node.js). In such a case, we have to call the shim command to correctly run on Windows, otherwise we get an error like below:
```
Error running eslint_d: ENOENT: no such file or directory
```
Solution
====
Make a wraper around for such linters to call the shim command using cmd.exe.
Note
====
I applied the wrapper function `call_with_cmd_exe_on_windows` to some linters installed by npm in haste. But I guess there is other linters that should be wrapped.
Related change
====
<https://github.com/neovim/nvim-lspconfig/pull/1522>
=> Fix: linters installed by npm doesn't work on Windows

lua/lint.lua
store process handles on each `try_lint()` call on a per-buffer basis, cancel processes that are still running on every `try_lint()` call
part 2/2 of #302
=> cancel previously spawned processes ( fix #302 )

README.md, lua/lint/linters/php.lua, tests/php_spec.lua
This one picks up basic syntax errors using PHP's built-in linter (`php -l`).
It would be good to add this to nvim-lint, since other tools support this:
- [ALE](https://github.com/dense-analysis/ale/blob/master/ale_linters/php/php.vim)
- [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/php.lua)
=> Add Support for PHP's built-in linter

lua/lint/linters/phpmd.lua, tests/phpmd_spec.lua
Makes violations easier to fix.
_Without_ this change, you might see this in [Trouble](https://github.com/folke/trouble.nvim):
```
Avoid variables with short names like $id. Configured minimum length is 3. phpmd [36, 1]
```
_With_ this change, you'd see this instead:
```
Avoid variables with short names like $id. Configured minimum length is 3. phpmd (ShortVariable) [36, 1]
```
By way of justification, you might want to add an annotation that looks like this:
```php
/**
* @SuppressWarnings(PHPMD.LongVariable)
*/
```
Having easy access to PHPMD rule name makes this much easier.
=> PHPMD: Set diagnostic code to be PHPMD rule name

lua/lint/linters/eslint_d.lua, tests/eslint_d_spec.lua
eslint_d can read from stdin, but it's currently not configured to do so.
With this change, we can now lint on "TextChanged" and "InsertLeave"
=> Configure eslint_d to read from stdin

lua/lint/linters/staticcheck.lua
Unfortunately `staticcheck` is not able to process stdin (at least in version 2023.1.3 (v0.4.3)). Therefore the default configuration should use the filename instead.
```
λ cat ./pkg/metrics/metrics.go | staticcheck -f json
{"code":"compile","severity":"error","location":{"file":"","line":0,"column":0},"end":{"file":"","line":0,"column":0},"message":"no Go files in ."}
```
When setting `stdin` to `false` everything seems to work.
=> staticcheck: don't use stdin

README.md, lua/lint/linters/tfsec.lua, tests/tfsec_spec.lua
Including tfsec as a linter. Works as intended on my 4-5 manifests.
Only shows the actual lint messages if the filename matches what the linter is pointing out (prevents random messages showing up in non active files)
Tests added but struggled to make them work, would appreciate some guidance there.
Heavily inspired by how null-ls did it.
=> adding tfsec lint

lua/lint/linters/ruff.lua
Relevant discussion: https://github.com/astral-sh/ruff/discussions/5857#discussioncomment-6583943
Arguments provided to every Ruff invocation by `ruff-lsp`:
https://github.com/astral-sh/ruff-lsp/blob/d642bed6c91fcfdaa29c84555575d069d178146b/ruff_lsp/server.py#L99-L108
=> Add `--force-exclude` to Ruff args

lua/lint/linters/djlint.lua
Thanks to Daniele for the original `djlint` support.
This PR is derived from it, fixes the pattern (as [the linter rules are prefixed by a letter](https://www.djlint.com/docs/linter/#rules) and the capture group should be `(%a%d+)`), and modifies the implementation to read from stdin.
- Change stdin key from false to true.
- Remove filename from pattern, groups, and args.
- Add - to args so djlint knows to read from stdin.
- Fix pattern to capture codes properly.
=> Configure djlint to read from stdin

README.md, lua/lint/linters/buildifier.lua
Supports both, parsing the warnings from the stdout and the syntax error messages from the stderr. This has been tested with the latest `buildifier` version installed via williamboman/mason.nvim.
=> feat: add buildifier linter support

lua/lint/linters/cspell.lua
inspired by [Fix eslint ](https://github.com/mfussenegger/nvim-lint/pull/314) 0b99416, change cspell lint config
=> Run cspell linter installed by npm via cmd.exe on Windows

lua/lint/linters/janet.lua
When run with `janet -k`, input will be read from stdin. This change allows this linter to be used with events like `TextChanged` and `InsertLeave`.
=> Allow Janet linter to use stdin

lua/lint/linters/shellcheck.lua
Quick successive changes result in this error:
```
  Error  20:06:23 msg_show.lua_error Error executing vim.schedule lua callback: ...hare/nvim/lazy/nvim-lint/lua/lint/linters/shellcheck.lua:17: Expected value but found T_END at character 1
stack traceback:
[C]: in function 'decode'
...hare/nvim/lazy/nvim-lint/lua/lint/linters/shellcheck.lua:17: in function 'parse'
...ser/.local/share/nvim/lazy/nvim-lint/lua/lint/parser.lua:123: in function <...ser/.local/share/nvim/lazy/nvim-lint/lua/lint/parser.lua:119>
```
checking whether there is actual output fixes that.
=> fix: shellcheck error when making quick successive changes

lua/lint/linters/pylint.lua
same issue as in #350, only for `pylint`
=> Handle empty output in `pylint` to avoid JSON decode errors

lua/lint.lua
Closes #338.
Very naive but appears to work fine.
=> Allow specifying `cwd` per linter

lua/lint/linters/terraform_validate.lua
Mostly [copied from null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/terraform_validate.lua), requires #358 to work properly for terraform modules that don't match nvim's pwd.
=> Add `terraform_validate` linter

README.md, lua/lint/linters/rpmspec.lua, tests/rpmspec_spec.lua
This adds a linter for RPM spec files.
I miss a simple `make test` to quickly run the tests ...
=> Add linter for rpmspec

lua/lint/parser.lua
More general approach to https://github.com/mfussenegger/nvim-lint/pull/365
Instead of fixing each linter one by one, just don't call them if there
is not output.
=> Don't call parse on empty outputs

lua/lint/linters/phpcs.lua, tests/phpcs_spec.lua
This change includes the source of PHP_CodeSniffer errors/warnings in diagnostic messages.
This means that instead of seeing a diagnostic message like this:
```
Line indented incorrectly; expected 4 spaces, found 5 phpcs [14, 6]
```
... you'll instead see one like this:
```
Line indented incorrectly; expected 4 spaces, found 5 phpcs (Generic.WhiteSpace.ScopeIndent.IncorrectExact) [14, 6]
```
This makes it much easier to disable/enable specific sniffs with a comment like this:
```
// phpcs:disable Generic.WhiteSpace.ScopeIndent.IncorrectExact
```
See https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file for more info.
=> feat: set code for PHPCS violations

lua/lint/linters/eslint.lua
tested and this works without issue.
this is much better than using the filename, because with this it's possible to lint an unsaved file too.
=> eslint: use stdin instead of filename

lua/lint/parser.lua
This call-site of `on_done` was missing `cwd`, breaking instances where concatenating `linter_cwd` to the parser file path was necessary.
This PR forwards that arg so that `stream = "both"` works.
=> Add cwd arg to fix stream = "both" when linter_cwd concat is needed

lua/lint/linters/jsonlint.lua
Updated jsonlint parser uses stdin. Now linter updates without writing to file.
=> Use stdin with jsonlint

lua/lint/linters/languagetool.lua
This PR fixes a parsing error when using LanguageTool (`languagetool`) linter for situations where the output JSON is prefixed with an error string.
Previously it would fail the linting, whereas now it parses the JSON correctly.
The warnings are displayed using `vim.notify_once` which annoyingly requires a confirmation. I didn't find any other way to log this. Looked for some logging mechanism in the plugin, but failed to find it if it exists. Saw that the PHP linter used the same tactic (albeit for an error-and-bail rather than a notify-and-continue situation).
The message looks like this:
```
WARN: no common words file defined for Japanese - this language might not be correctly auto-detected
WARN: no common words file defined for Khmer - this language might not be correctly …
```
=> languagetool: Fix parsing error when output contains 'Err:...'

lua/lint/linters/eslint.lua, lua/lint/linters/eslint_d.lua, tests/eslint_d_spec.lua
This PR aims to add end_col support for the `eslint` and `eslint_d` linters. 
See https://github.com/mfussenegger/nvim-lint/issues/394 for background.
=> fix: support end col for eslint

README.md, lua/lint/linters/trivy.lua, tests/trivy_spec.lua
=> feat(trivy): add trivy linter

lua/lint.lua
`require` already caches modules, no need to store them in a extra
table, it just messes with package.loaded cache reset.
Also fixes https://github.com/mfussenegger/nvim-lint/issues/408
=> Remove linters extra cache; return nil instead of err

lua/lint/linters/eslint.lua, lua/lint/linters/eslint_d.lua, tests/eslint_d_spec.lua
This PR aims to parse `eslint` JSON output, which will improve the diagnostics since it allows you to get more information, like `end_col`.
=> fix: parse eslint output with json

lua/lint/linters/mypy.lua, tests/mypy_spec.lua
This PR adds end column support for the `mypy` linter.
Also, there was no existing test coverage for this linter, so I added it. Tests are passing locally.
=> fix: support end col for mypy

lua/lint.lua
Calling `try_lint` multiple times for different linters could cancel the
wrong linters.
=> Only send sigterm to linters with the same name

lua/lint/linters/cpplint.lua
Fixed #445 using `utils.inject_cmd_exe`.
=> Fixed cpplint error on windows with inject_cmd_exe

lua/lint.lua, tests/compiler_spec.lua
85108b3 introduced a regression, causing fd leaks
Closes https://github.com/mfussenegger/nvim-lint/issues/448
=> Fix fd leak

lua/lint/linters/ruff.lua
JSON parsing for end_col (to get underlinesj
In addition, I disliked having warnings on all lints, so I copied the mapping from [ruff-lsp](https://github.com/astral-sh/ruff-lsp/blob/6a1a7b18711cf65b058492d5800e606f14556861/ruff_lsp/server.py#L346-L354)
=> ruff: Implement json parsing (for end_col) and basic code to severity mapping

lua/lint/linters/shellcheck.lua
Adds Windows support for `shellcheck`.
Thanks for your work on this plugin!
=> shellcheck: add Windows support

README.md, lua/lint/linters/zsh.lua
uses `zsh --no-exec`, similar to `fish`
=> Add `zsh` linter

lua/lint/linters/clangtidy.lua
Current clang-tidy linter is not working, because clang-tidy returns exit code 1 if linting produces errors.
=> Ignore exitcode for clang-tidy

lua/lint/linters/actionlint.lua
This PR makes `actionlint` read from `stdin`, see https://github.com/rhysd/actionlint/blob/0b676b1171cb62a16e4f942100cf046aa04aef21/docs/usage.md?plain=1#L20-L24.
I am not sure if check on line 18 is actually necessary. `actionlint`, when invoked without any arguments will [look for workflows in current repository](https://github.com/rhysd/actionlint/blob/0b676b1171cb62a16e4f942100cf046aa04aef21/docs/usage.md?plain=1#L8-L12), and only check [paths when given](https://github.com/rhysd/actionlint/blob/0b676b1171cb62a16e4f942100cf046aa04aef21/docs/usage.md?plain=1#L14-L18) some.
Currently `actionlint` is set up such that:`stdin = true` but no `-` in `args` results in no filename being passed to `args` and `actionlint` checking entire repository for workflow files. Therefore that check on …
=> Make actionlint actually use stdin

lua/lint/linters/tflint.lua, tests/tflint_spec.lua
👋  Thank you for all the work to maintain this plugin!
What
---
Update filename match to check relative path instead of absolute path.
Why
---
[`vim.api.nvim_buf_get_name(bufnr)`](https://neovim.io/doc/user/api.html#nvim_buf_get_name()) gets the full path name, but `tflint` only returns the relative path from the root of the project.
Use [`vim.fn.expand("%")`](https://neovim.io/doc/user/builtin.html#expand()) returns the current filename that is open in the buffer.
Example:
```sh
$ tflint --format=json | jq
{
"issues": [
{
"rule": {
"name": "terraform_typed_variables",
"severity": "warning",
"link": "https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_typed_variables.md"
},
"message": "`not_used` variable has no type",
"range": {
"filename": …
```
=> fix(tflint): path match

lua/lint.lua, tests/lint_spec.lua, tests/loop.py
Alternative for https://github.com/mfussenegger/nvim-lint/pull/483
Should also fix https://github.com/mfussenegger/nvim-lint/issues/484
=> Return all linters in get_running; add bufnr filter; fix proc cleanup

lua/lint/linters/flake8.lua
flake8 can be configured based on file path, to ignore certain files or change config options. But it only works if we pass in `--stdin-display-name`
=> Add `--stdin-display-name` option for flake8 linter

README.md, lua/lint/linters/dash.lua
Uses `dash -n` to check syntax of shell scripts without executing them.
This is similar to `zsh --no-exec` and `fish --no-execute`.
=> feat: add dash linter

lua/lint/linters/credo.lua, lua/lint/linters/statix.lua, lua/lint/parser.lua, tests/credo_spec.lua
373968190b0022be80a6099ecb483cfc2b5fe8af introduces a new parameter `bufnr` that only displays the lint if the item buffer matches `bufnr`. However, parsers that read their input from stdin (`stdin = true`) either do not report a buffer (in which case `item.bufnr` is 0) or incorrectly report their buffer as some variant of `stdin`, `<stdin>`, etc. (when the filename used to be parsed with `%f`).
According to `:help getqflist()`, an item with without a buffer will have `item.bufnr` be 0. 
> Quickfix list entries with a non-existing buffer number are returned
> with "bufnr" set to zero (Note: some functions accept buffer number zero
> for the alternate buffer, you may need to explicitly check for zero).
In this case, we should show the lints. 
Additionally, certain linters (credo, statix) …
=> fix(lua/lint/parser.lua): `from_errorformat` and `stdin = true` parsers

lua/lint/linters/psalm.lua
Using Psalm, I had a strange bug where diagnostics for other files were showing in my buffer.
After some testing, I saw that Psalm is outputting diagnostics for the all project (even with `lint.linters.psalm.append_fname = true` and `lint.linters.psalm.stdin = false`).
I fixed it by checking if the message from Psalm is about the current buffer and only creating diagnostic if it is.
Another fix could be to set the bufnr to to the diagnostic table, but that would involve checking each of the open buffers and it's filename.
I'm pretty new to Neovim, please ignore and close if I'm making no sense and if it's just a config problem on my end.
=> PHP Psalm - fix incorrect diagnostics

lua/lint/linters/biomejs.lua
This PR is to adjust `biomejs.lua` linter interface to use local `biome` if it is installed in `node_modules`.
This is to match the behavior from the `eslint` and `eslint_d` linter interfaces.
=> biome: use local biome from node_modules if present

README.md, lua/lint/linters/saltlint.lua, tests/saltlint_spec.lua
PR to add the `salt-lint` linter for Salt / SaltStack, along with tests.
https://github.com/warpnet/salt-lint
The name `saltlint` (without the dash) was chosen to make it a little easier for a user to add args in their config, with something like the following.
```lua
local saltlint = require("lint").linters.saltlint
table.insert(saltlint.args, 1, "-t")
table.insert(saltlint.args, 2, "209")
```
Thanks!
-----------
Notes:
- `salt-lint` is one of the linters supported by [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) ( in [lua/null-ls/builtins/diagnostics/saltlint.lua](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/saltlint.lua) ).
- I also submitted a PR to get `salt-lint` added to the mason registry …
=> feat: add salt-lint

lua/lint/parser.lua
Hello,
The change helps to avoid col and lnum values less than 0.
I faced problems with cppcheck 2.12.0. It can report zero line/column number if a problem is located at the beginning of a file. After applying offsets, the value(s) can be < 0, triggering errors in other places. For example, in trouble.nvim plugin because it can't jump on an invalid source location. The limiting of minimal values helped with the problem.
Here is example of cppcheck report with line/column = 0
```
Checking src/hash.cpp ...
src/hash.cpp:0:0: information: Too many #ifdef configurations - cppcheck only checks 12 of 20 configurations. Use --force to check all configurations. [toomanyconfigs]
^
src/hash.cpp:1:0: information: Include file: <noheader.h> not found. Please note: Cppcheck does not need standard …
```
=> parser:add minimal limit for col & lnum

README.md, lua/lint/linters/vala_lint.lua
Hi,
I implemented the Vala linter.
I got a copy of [tfsec linter](https://github.com/mfussenegger/nvim-lint/blob/master/lua/lint/linters/tfsec.lua) and changed it to make it compatible for Vala lang.
Sample vala-lint output:
```bash
$ io.elementary.vala-lint -j -e sample.vala | jq .
{
"mistakes": [
{
"filename": "sample.vala",
"line": 5,
"column": 21,
"endLine": 5,
"endColumn": 23,
"level": "error",
"message": "Expected a single space",
"ruleId": "double-spaces"
},
{
"filename": "sample.vala",
"line": 21,
"column": 25,
"endLine": 21,
"endColumn": 27,
"level": "error",
"message": "Expected a single space",
"ruleId": "double-spaces"
}
]
}
```
Result:
=> Add Vala linter

lua/lint/linters/cppcheck.lua
This is a fix of #492 for cppcheck. 
Now we check if build directory exists before passing the argument to cppcheck.
=> fix: Check if build directory exists for cppcheck 

lua/lint/linters/golangcilint.lua
This PR allows `golangcilint` to use provided `cwd` instead of `vim.fn.getcwd()` using functionality that was added in https://github.com/mfussenegger/nvim-lint/pull/358
It might be helpful for a monorepo with multiple languages.
```bash
project-root
├── .golangci.yaml
├── client
│   └── lxc.py
├── agent
│   ├── go.mod
│   └── cmd
│       └── main.go
└── core
├── go.mod
└── main.go
```
If my `vim.fn.getcwd()` will be `project-root` I won't be able to run `golangcilint` since it will fail to find any Go modules
```
ERRO [linters_context] typechecking error: pattern ./...: directory prefix . does not contain main module or its selected dependencies
```
However, with some auto commands I can search for `go.mod` among ancestors that are related to my buffer path:
```lua …
```
=> fix: golangci-lint respect cwd

lua/lint/linters/typos.lua
At least with recent `typos` (I have 1.18.1) the `line_num` is not returned when the typo is discovered on the first line of the document. Only `byte_offset` is returned. This causes a *parser error* to appear at the top of the file in vtext.
=> fix(typos): line_num is not always returned

lua/lint/linters/rubocop.lua
Add --stdin and --server option to rubocop
[Rubocop Server Mode](https://docs.rubocop.org/rubocop/usage/server.html) launchs deamon process and speed up launch time of rubocop.
=> rubocop: Add --server and --stdin options to rubocop

README.md, lua/lint/linters/markuplint.lua, tests/markuplint_spec.lua
1. Add `markuplint` support.
- homepage: https://markuplint.dev/
- CLI reference: https://markuplint.dev/docs/guides/cli
2. Update readme.
=> feat: add markuplint support

lua/lint/linters/clj-kondo.lua
Diagnostics appear one character too far to the right.
=> Fix off-by-one column in clj-kondo

lua/lint/linters/perlcritic.lua
Small change to maintain compatability with older versions
=> vim.uv requires nvim 0.10 or higher, use vim.loop instead

lua/lint/linters/pylint.lua, tests/pylint_spec.lua
```
"symbol": "subprocess-popen-preexec-fn",
"message": "Using preexec_fn keyword which may be unsafe in the presence of threads",
"message-id": "W1509"
```
Use the message symbol to know which rule it references, the id is hard to understand.
=> feat: Add message symbol to pylint errors

lua/lint/linters/ansible_lint.lua
The output of `ansible-lint` was colored (at least on my machine). This lead to the parser failing to parse any diagnostics. By setting the `--nocolor` the diagnostics began to show up properly.
I also checked some other parsers and many of them had colors disabled, so this should probably be the case for `ansible-lint` too.
=> fix(ansible-lint): add --nocolor argument

lua/lint/linters/trivy.lua
`result.Misconfigurations` can be a nil value.
I encountered this by explicitly ignoring two Terraform misconfiguration rules.
In the example below, there are two #trivy:ignore comments.
Having two ignore comments results in `result.Misconfigurations` being nil. 
```
#trivy:ignore:AVD-AWS-0089
resource "aws_s3_bucket" "this" {
bucket = "some-bucket-name"
}
#trivy:ignore:AVD-AWS-0132
resource "aws_s3_bucket_server_side_encryption_configuration" "this" {
bucket = aws_s3_bucket.this.id
rule {
apply_server_side_encryption_by_default {
sse_algorithm = "AES256"
}
}
}
To solve this, I followed the pattern from two lines above where possible falsy value was pair with an "or {}".
=> trivy: Handle nil result misconfigurations

README.md, lua/lint/linters/markdownlint-cli2.lua
Hi there,
I figured markdownlint doesnt provide a proper and fast CLI for linting markdown files, more importantly in my neovim projects I can't put my linter configurations to package.json with other tools: `markdownlint` or `markdownlint-cli`. This is the only one that provides this option.
I don't know whether declaring the linter here triggers mason download of the said package `markdownlint-cli2`, however I tested that this contribution works when I have `markdownlint-cli2` installed. Hope this is sufficient for adding this linter to `nvim-lint`.
=> Add markdownlint-cli2 for package.json configuration & speed

lua/lint/linters/trivy.lua, tests/trivy_spec.lua
**Changes**
* bugfix: no longer reports trivy StartLine, EndLine as nvim-lint col, end_col
* bugfix: check parsed fields before building/inserting diagnostic
* cleanup: fix deprecated CLI arg: '--scanners config' -> '--scanners misconfig'
* comments: clarify intent to ease future maintainence
**Bug Descriptions**
Output from trivy sometimes includes line info, but not column info.  line info is used for both col and lnum in trivy.lua
Output from trivy does not always contain StartLine and EndLine fields.  When they are missing, diagnostics are not created for each Misconfiguration from trivy, but instead a single diagnostic is generated with a lua error about accessing a nil value (StartLine).
To reproduce, open the following Dockerfile with trivy enabled as a linter, then look at the …
=> trivy: bugfix: line reported as col; bugfix: crash on missing line from trivy; plus refinements

lua/lint/linters/stylelint.lua
According to https://github.com/mfussenegger/nvim-lint/pull/518 using
`both` should work for the latest stable version but also older versions
=> stylelint: set stream to both

lua/lint/linters/codespell.lua
This PR enables the stdin mode for codespell.
This is a follow-up PR to https://github.com/mfussenegger/nvim-lint/pull/457 after the codespell has been released with required changes which simplify the output parsing.
=> codespell: use stdin

README.md, lua/lint/linters/ghdl.lua
Adds a VHDL linter using [GHDL](https://github.com/ghdl/ghdl) discussed in #253, but which was never actually implemented.
=> Add ghdl linter

README.md, lua/lint/linters/spectral.lua
Hi @mfussenegger,
thanks for this great plugin.  
I would like to add the [Spectral](https://docs.stoplight.io/docs/spectral/674b27b261c3c-overview) linter for OpenAPI specifications.
There is a slight problem in that the linter takes a *required* parameter `--ruleset` that takes either a file path or a URL.  
Without this parameter, the linter will error out.
I have implemented it in a way, where the user would have to do something like this, which is a bit awkward 😄
```lua
require('lint').linters.spectral = require('lint').linters.spectral("path/to/ruleset")
```
Another approach would be to not specify the ruleset parameter by default, let the linter error and let the user figure out how to override the linters `args`. This is also pretty inconvenient.
I would appreciate your feedback …
=> feat: add spectral

lua/lint/linters/ruff.lua
Use `ruff check` subcommand instead of relying on the default behavior which has been deprecated and will be removed in v0.5: https://github.com/astral-sh/ruff/pull/12011.
=> Use `ruff check` subcommand

README.md, lua/lint/linters/vsg.lua
Adds the [VHDL Style Guide](https://github.com/jeremiah-c-leary/vhdl-style-guide) (VSG) linter.
The linter doesn't autodetect configuration files, so I added functionality to look for `.vsg.yaml` and `.vsg.json` in the file's directory and in `xdg-config/vsg` or `~/.config/vsg`. I could not find any mention of a standard name for said files in the documentation, but I read some people using these names and so do I. I'm not sure if this is out of scope, but it is quite nice. Please let me know.
=> Add VSG linter

lua/lint/linters/eslint.lua
Closed #462
When there's no ESLint config, the error is shown in the buffer, which is an annoying experience when a user is working on JS-related files that are not associated with a config.
We should warn the user of the error once instead of showing the error in the buffer:
=> fix(eslint): warn user of no config file instead of showing in buffer

lua/lint/linters/cspell.lua
CSpell parser doesn't calculate Unicode string length right.
```lua
string.len('Йоу') -- cyrillic string return 6 instead of 3
```
Lua 5.1 doesn't have a standard library for unicode strings, so I used a Vim function.
=> fix: unicode string length

lua/lint/linters/mypy.lua
At the moment, the plugin will just run the global `mypy`, which, if installed via mason, will then only use system-level python3. If the user hasn't installed mypy through mason but has mypy installed in their locally activated python environment, it works fine though but I feel that's a bit suboptimal as you then need to install mypy into every custom environment you make.
To fix this I initially added the following to my nvim-lint config block:
```lua
vim.list_extend(lint.linters.mypy.args, {
'--python-executable',
function()
return vim.fn.exepath 'python3' or vim.fn.exepath 'python'
end,
})
```
and this works pretty much perfectly and should also work cross platform with basically any virtual env management system. This PR simply integrates this into the mypy configuration in …
=> fix(mypy): make mypy respect the current python environment

lua/lint/linters/clippy.lua
Sorry, I should have tested it out beforehand. Clippy returns the source file as relative to the directory and I had completely forgotten nvim_buf_get_name() returns the file as an absolute path.
=> fix(clippy): use relative path instead of absolute

README.md, lua/lint/parser.lua, tests/parser_spec.lua
An alternative and more general approach to https://github.com/mfussenegger/nvim-lint/issues/625
=> Add support for lpeg patterns and match functions to `from_pattern`

lua/lint/linters/codespell.lua, lua/lint/parser.lua, tests/codespell_spec.lua
Alternative to https://github.com/mfussenegger/nvim-lint/pull/602
Given that the linter doesn't actually output col/end_col information
this looks for the misspelled words in the buffer
Note that if the same misspelled word occurs more than once in a line,
it will erroneously report all the errors in the first location.
=> codespell: Provide col/end_col information

lua/lint.lua
#648 indicates that `C:\WINDOWS\system32\cmd.exe` takes over tab title even when `:set title`. Setting `options.hide` in `uv.spawn` can hide the subprocess console window, and display title on the tab.
Closes #648.
=> fix: prevent cmd.exe taking over tab title

lua/lint/linters/sqlfluff.lua, tests/sqlfluff_spec.lua
Sqlfluff does not provide severity codes in its messages. The original defaulted everything to `ERROR`. This change downgrades regular messages to `WARN` and only flags the code for a parsing error as `ERROR`. This is done because Sqlfluff formatting will fail if a parsing error occurs, and identifying the error is much easier when a distinction is made between errors and warnings.
=> fix(sqlfluff): Disambiguate sqlfluff diagnostics

README.md, lua/lint/linters/awk.lua
This PR adds a awk linter using (g)awk. I'm unsure if it instead should be called gawk, seeing as there are quite a few different AWK interpreters, and it's the gnu one that provides this linting functionality. I don't know about all the others. I saw [conform.nvim](https://github.com/stevearc/conform.nvim) use awk so I did as well.
Let me know what you think.
=> Add awk linter

lua/lint/linters/revive.lua
Use `revive`'s JSON formatter so we can get severities in diagnostics and less error prone diagnostics.
=> feat(revive): use JSON formatter, proper severities

lua/lint/linters/credo.lua, tests/credo_spec.lua
I changed credo spec to pass around the filename. This is important because credo has defaults that disable some checks for certain directories. And if the repo has a `.credo.exs` file, credo needs to know the filename that it is checking.
I also created the severity mapping.
(I could not run the tests on my machine, so I want to run the CI to see if everything works).
=> fix(credo): credo now respects .credo.exs

lua/lint/linters/phpinsights.lua
Architecture diagnostics lack the line number and the message field is named title.
closes #624
=> fix: default values for missing fields

README.md
The example config in Usage section has a format error.
This
```lua
markdown = {'value',}
```
should be
```lua
markdown = {'value'},
```
=> fix: format error in README example

lua/lint/linters/markdownlint.lua, tests/markdownlint_spec.lua
`markdownlint` supports standard input with option `--stdin`. Enabling standard input can help neovim update diagnostics for `InsertLeave` and `TextChanged` events.
=> feat: support markdownlint with standard input

lua/lint/linters/verilator.lua, tests/verilator_spec.lua
Issue: Earlier diagnostics of all files(in the included directories) for a line number was shown in the currently open buffer. Fix: Now the behaviour is normal since nvim-lint can now detect the file name and will show diagnostics relevant to the current buffer only.
=> fix(verilator): added file group

lua/lint/linters/mypy.lua, spec/mypy_spec.lua
Capturing mypy [error codes](https://mypy.readthedocs.io/en/stable/error_code_list.html) to use in diagnostics.
=> feat: capture mypy error codes

doc/lint.txt, lua/lint.lua
The luadoc says that the stream field is optional, and the usage reflects that. I made the type optional. Also setting a particular stream value doesn't seem to work for lua_ls so I corrected the union type.
=> chore: fix stream type

lua/lint/linters/protolint.lua
After debugging an nvim-lint/protolint crash I got in a proto file, it turns out that the `json_output.lints` can be `vim.NIL` (not `nil`).
Extend the nilcheck with checking for `vim.NIL`.
=> fix(protolint): check for vim.NIL

README.md, lua/lint/linters/sphinx-lint.lua, spec/sphinx-lint_spec.lua
This adds support for sphinx-lint, the linter provided by Sphinx here: https://github.com/sphinx-contrib/sphinx-lint
=> Add sphinx-lint support

lua/lint/parser.lua
As the absolute Path recognition only works for linux style paths in the match function of the parser. Linter that output absolute paths were not working on windows.
=> Fix absoulte path recognition on windows in parser

README.md, lua/lint/linters/dmypy.lua, spec/dmypy_spec.lua
Adds `dmypy` as a linter, which contains mostly the same interface as `mypy` but it is ran in a daemon process.
I've been using `dmypy` for a bit in my own setup as it has been working well.
I haven't been able to run the tests locally as I can't seems to get `busted` working.
=> Add dmypy linter

lua/lint/linters/clj-kondo.lua
As the [documentation for `clj-kondo` specifies](https://github.com/clj-kondo/clj-kondo/blob/d7dff3762a7fad581da56d15b026f537e3623438/analysis/README.md#data), end-col and end-row are returned in some circumstances.
This patch will prefer end-col and end-row, if they are returned. 
It enables underlining for many diagnostics.
=> Update end_lnum and end_col for clj-kondo

lua/lint/linters/terraform_validate.lua
`terraform validate` starts validation from the cwd (unless `-chdir` is used), when we want to validate just some file (actually directory as it cannot validate just one file), instead of changing cwd we have to pass it as an argument.
=> Pass relative path to terraform validate instead of changing cwd

lua/lint/linters/terraform_validate.lua
This ensures `terraform validate` is aware of `.terraform/` and does not report false positives for missing  (uninstalled) modules.
More information in comment on PR that originally changed that: https://github.com/mfussenegger/nvim-lint/pull/694#issuecomment-2558669860.
=> fix(terraform_validate): pass `-chdir=` to `terraform` command

lua/lint/linters/fish.lua
The error message generated by `fish --no-execute` varies by locale. For instance:
```sh
$ cat test.fish
|
$ LANG=C fish --no-execute test.fish
test.fish (line 1): Expected a string, but found a pipe
|
^
warning: Error while reading file test.fish
$ LANG=pl_PL.UTF-8 fish --no-execute test.fish
test.fish (linia 1): Expected a string, but found a pipe
|
^
warning: Wystąpił błąd podczas odczytywania pliku test.fish
```
This means that hardcoding the word `line` into the errorformat is too strong. This commit replaces it with an arbitrary string not containing a space character (`%[%^ ]%#`).
Fixes #708.
=> fix(fish): allow an arbitrary word before line number

lua/lint/linters/cfn_lint.lua
This ignores the exit code of cfn-lint. cfn-lint only uses it to communicate
what it found.
=> fix(cfn-lint): ignore exit code

lua/lint/linters/ghdl.lua
GHDL provides the severity of its diagnostics. For example:
```
test/tb_lfsr.vhd:7:20:error: no declaration for "std_logic"
signal clk   : std_logic;
^
test/tb_lfsr.vhd:8:20:error: no declaration for "std_logic"
signal arst  : std_logic;
^
test/tb_lfsr.vhd:9:20:error: no declaration for "std_logic_vector"
signal value : std_logic_vector(15 downto 0);
^
test/tb_lfsr.vhd:7:12:warning: signal "clk" is never referenced [-Wunused]
signal clk   : std_logic;
^
test/tb_lfsr.vhd:8:12:warning: signal "arst" is never referenced [-Wunused]
signal arst  : std_logic;
^
test/tb_lfsr.vhd:9:12:warning: signal "value" is never referenced [-Wunused]
signal value : std_logic_vector(15 downto 0);
```
I don't know if it will ever produce any other kind of severity. But these two seem to be the most common.
=> Parse GHDL diagnostic severity

lua/lint/linters/ghdl.lua
Before:
```
ghdl:  no declaration for "unsigned"
```
After:
```
ghdl: no declaration for "unsigned"
```
Also, use `(%l+)` instead of `([^:]+)` as severity seems to be always lowercase
`error` or `warning`.
=> ghdl: trim whitespace

lua/lint/linters/mypy.lua
mypy outputs the errors to `stdout` by default but the following
configuration options can change the behavior to output them on
`stderr`:
install_types = "True"
non_interactive = "True"
`stream = "both"` should handle both cases.
Closes https://github.com/mfussenegger/nvim-lint/issues/700
=> mypy: set stream to "both"

README.md, lua/lint/linters/sqruff.lua
Added [sqruff](https://github.com/quarylabs/sqruff) to the list of available linters (a new tool inspired by Python's `ruff` and `sqlfluff`)
I've added with stdin support + json parsing; though their JSON-format output lacks the error codes (I made an issue: https://github.com/quarylabs/sqruff/issues/1219)
This was heavily inspired by the `phpcs`-implementation :-)
Let me know if I can improve it somehow
=> feat: added sqruff

lua/lint/linters/golangcilint.lua
Compare absolute paths when determining filename to buffer matching
=> golangci-lint: handle relative paths while parsing (#730)

lua/lint/linters/golangcilint.lua
Add arg to golangci-lint to not error exit when finding lint.
This allows error exit code to indicate failure to run the linter itself, update the linter config to not ignore error exit
=> golangci-lint: do not exit error when finding lint

lua/lint/linters/sqruff.lua
It was fixed rather quickly upstream:
Want me to provide a backwards compatible `code = msg.code or nil` thing?
Ref: https://github.com/mfussenegger/nvim-lint/pull/728
=> feat(sqruff): include error code in diagnostic

lua/lint.lua
Stole this contribution from [this PR](https://github.com/mfussenegger/nvim-lint/pull/688) since I do not have permissions to push to that branch and do not wish to continue maintaining my fork with this change. Minimized the contribution so that we only do the `vim.defer_fn` instead of `vim.wait` to remove the complexity of handling orphaned processes. As a side note, the handling of the orphaned processes on `VimLeavePre` caused my editor to freeze when exiting, so the change was not desirable for me anyways.
=> fix: do not block UI when cancelling lint

README.md, lua/lint/linters/twig-cs-fixer.lua, spec/twig-cs-fixer_spec.lua
Adds a linter for [`twig-cs-fixer`](https://github.com/VincentLanglet/Twig-CS-Fixer).
A similar tool to the already-supported [`twigcs`](https://github.com/friendsoftwig/twigcs), `twig-cs-fixer` now seems to be the linter/fixer [recommended by the Twig project](https://twig.symfony.com/doc/3.x/coding_standards.html).
=> feat: add support for twig-cs-fixer

.projections.json
Adds support for [Projectionist](https://github.com/tpope/vim-projectionist)'s Alternative Files feature.
This allows very fast switching between spec and implementation files (just hit `:A`)
=> feat: add support for Vim Projectionist

lua/lint/linters/golangcilint.lua
This is a fix for v2 of golangci-lint that clears out any alternative output paths that could be found in the config file.  This allows users to set whichever output format they'd prefer in the config file, while ensuring the linter is properly configured for use with this plugin. 
In v1, setting the output format would overwrite all other possibly set values in the config file, which is changed now in v2.
Discussion in #761
=> golangci-lint: clear alt output format paths to overwrite .golangci.yml

lua/lint/linters/phpstan.lua, spec/phpstan_spec.lua
Occassionally, one needs to ignore a rule as described at https://phpstan.org/user-guide/ignoring-errors
Having the name of the readily available is much better than having to search the web for it, as I otherwise find myself doing.
=> feat: Set diagnostic code in PHPStan linter

lua/lint/linters/credo.lua
we don't parse the filename anymore since it's now always 'stdin'.
=> credo: use stdin to communicate with the linter

lua/lint/linters/oelint-adv.lua, spec/oelint-adv_spec.lua
Starting from commit:
```
commit a620ab1cefdeeef35f2e17150534b31d9a362529
Author: Konrad Weihmann <kweihmann@outlook.com>
Date:   Tue Aug 27 12:18:24 2024 +0000
```
`oelint-adv` adds `[branch:XXX]` to the end of the output line regardless of the provided `--messageformat`. So the output needs to be parsed correspondingly as it contains extra ':' symbol now.
=> [FIX] oelint-adv: fix parse pattern to support oelint-adv `[branch:XXX]`

README.md, lua/lint/linters/redocly.lua
`redocly lint` is an [OpenAPI linter](https://redocly.com/docs/cli/commands/lint). The best format I found is `codeclimate`, although it doesn't return anything about the location except the line number. For OpenAPI specs, it's usually thou enough.
=> feat(linters): add redocly

lua/lint/linters/fortitude.lua
Fortitude doesn't read from stdin and just give suggestions for every file in the same directory. This now has the side effect that suggestions get displayed in the wrong files. This PR fixes this simple overside.
=> fix: fortitude doesn't read from stdin

lua/lint/linters/zizmor.lua
zizmor seems to only provide diagnostics for the given file, so the
filtering isn't needed and the used property was wrong. v1.6.0 uses
`given_path` instead of `path`.
This also adds the symbolic.annotation info and the URL with more
details to the message.
=> zizmor: Fix end_lnum; tweak message; remove bufpath filter

lua/lint/linters/zsh.lua
If not on Windows, read from `stdin`, allowing linting to be performed immediately without writing the file.
Note: if `/dev/stdin` is not referenced, the line number is not produced:
```
$ printf "( foo" | zsh --no-exec /dev/stdin
/dev/stdin:1: parse error near `foo'
$ printf "( foo" | zsh --no-exec -
zsh: parse error near `foo'
$ printf "( foo" | zsh --no-exec
zsh: parse error near `foo'
```
which will not work on Windows
=> Add support to `zsh` linter for linting without writing file

lua/lint/linters/shellcheck.lua
If you check the [shellcheck docs](https://github.com/koalaman/shellcheck/blob/20d11c1c33df71a375406c981a629269ee5149a2/shellcheck.1.md?plain=1#L188), you find that `json` is "a legacy version of the **json1** format. It's a raw array of comments, and all offsets have a tab stop of 8."
This modifies the shellcheck linter to use the `json1` format, which has existed for [at least 4 years](https://github.com/koalaman/shellcheck/commit/5ccaddbcc2455c7b5c753014b16dcb9f8ec78bdb).
This fixes column offsets when your shell script uses hard tabs and the `tabstop` setting is anything other than 8.
=> Use json1 format for shellcheck

lua/lint/linters/cfn_lint.lua
cfn-lint does support stdin
`echo 'Resources: {}' | cfn-lint`
=> fix(cfn-lint): use stdin

lua/lint/linters/golangcilint.lua
The value from `lintedfile_norm` is giving a wrong path. We can directly get the absolute path of the linted file by using `--path-mode=abs` flag. This fix is based on none_ls' [implementation](https://github.com/nvimtools/none-ls.nvim/blob/90e4a27ccaa25979a6b732b9f06dfa43b54957b7/lua/null-ls/builtins/diagnostics/golangci_lint.lua#L40).
=> fix(golangcilint): get absolute path from golangci-lint v2

README.md
Updates README to point to the correct successor.
> This repository has been abandoned. Its successor is [PHPCSStandards/PHP_CodeSniffer](https://github.com/PHPCSStandards/PHP_CodeSniffer/)
> — [squizlabs/PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/README.md?plain=1#L2)
=> Update PHP_CodeSniffer link

lua/lint/linters/ansible_lint.lua
This PR updates the `ansible-lint` errorformat to match the optional row in the parseable output:
```
$ ansible-lint -p example.yml
WARNING  Listing 2 violation(s) that are fatal
example.yml:18: no-free-form: Avoid using free-form when calling module actions. (service)
example.yml:19:7: fqcn[action-core]: Use FQCN for builtin module actions (service).
```
To match both formats the efm is updated to `%f:%l:%c: %m,%f:%l: %m`.
=> fix(ansible-lint): update efm to match all output formats

lua/lint/linters/oxlint.lua
Similarly to many other linters, if oxlint is available in the current project under node_modules/.bin, use that binary instead of a globally installed one.
=> oxlint: use local binary from node_modules if available

lua/lint/linters/stylelint.lua
According to https://stylelint.io/user-guide/node-api#errored:
> errored
> Boolean. If true, at least one rule with an "error"-level severity registered a problem.
This means that if stylelint outputs only warnings, `errored` will be set to `false`. Here's a real example:
```
[
{
"source": "insight-regression-indicator.less",
"deprecations": [],
"invalidOptionWarnings": [],
"parseErrors": [],
"errored": false,
"warnings": [
{
"line": 3,
"column": 1,
"endLine": 3,
"endColumn": 2,
"rule": "selector-disallowed-list",
"severity": "warning",
"text": "Unexpected selector \"*\""
}
]
}
]
```
However, creation of diagnostics from `stylelint`'s output is guarded by a `if decoded.errored` which means that in situations like above where only warnings are emitted, these warnings are not shown. 
With …
=> stylelint: warnings unreported if no errors present

lua/lint/linters/rpmspec.lua
This adapts the linter definition for f92c6e16
=> rpmspec: Fix function signature
